#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

article="$1"

[ -z "$article" ] && {
  echo "ERROR: invalid article"
  exit 1
}

$DIR/share/get-article $article | \
  $DIR/share/parse
