#!/bin/bash

listing="$1"

[ ! -e $listing ] && {
  echo "ERROR: invalid file"
  exit 1
}

temp=$(mktemp)
(grep '\d\.' $listing || \
  grep '\d\s\{2,\}' $listing) \
  >$temp

endi=$(awk -F '.' '{print $1}' $temp | sort -n -r | head -n1)
sed -e '1,/'"$endi"'\./!d' \
    -e 's/^[ 0-9]*\. \{1,\}\"\([^"]*\)\".*$/\1/' \
    -e 's/^[ 0-9]*\. \(.*\) (.*) -.*$/\1/' \
    -e 's/^[ 0-9]*\. \(.*\) ([^()]*) [0-9].*$/\1/' \
    -e 's/^[ 0-9]*\. \(.*([^()]*)\) .*$/\1/' \
    -e 's/^[ 0-9]*\. \([^()]*\) .*$/\1/' \
    -e 's/^[ 0-9]* \{1,\}\"\(.*\)\".*$/\1/' \
    $temp
